version: '3.8'

services:
  ssfrp:
    image: ssserverfrp
    container_name: myssserverfrp
    environment:
      - SSSERVER_METHOD=2022-blake3-chacha20-poly1305
      - SSSERVER_PASSWD=yt+S5v1oBLqirPlyGD+rn+cAOnVDZnJcTT9QpbST7HU=
      - FRPC_SERVER=
      - FRPC_SERVER_PORT=
      - FRPC_TOKEN=
      - FRPC_REMOTE_PORT=10040
    ports:
      - "8848:8848/tcp"
      - "8848:8848/udp"
    restart: always

